spring.application.name=MedSys
#server.port = 9009
#
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/medsys
#spring.datasource.username=root
#spring.datasource.password=Irphan@1234